// ==================== Enums as constants (SQLite doesn't support enums) ====================

export const ROLES = {
  ADMIN: "ADMIN",
  MANAGER: "MANAGER",
  SECRETARIAL_STAFF: "SECRETARIAL_STAFF",
  ACCOUNTING_STAFF: "ACCOUNTING_STAFF",
  TAX_STAFF: "TAX_STAFF",
  AUDIT_STAFF: "AUDIT_STAFF",
} as const;

export const DEPARTMENTS = {
  SECRETARIAL: "SECRETARIAL",
  ACCOUNTING: "ACCOUNTING",
  TAX: "TAX",
  AUDIT: "AUDIT",
  MANAGEMENT: "MANAGEMENT",
} as const;

export const CASE_STATUS = {
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  AWAITING_CLIENT: "AWAITING_CLIENT",
  AWAITING_INTERNAL_REVIEW: "AWAITING_INTERNAL_REVIEW",
  BLOCKED: "BLOCKED",
  READY_FOR_SUBMISSION: "READY_FOR_SUBMISSION",
  SUBMITTED: "SUBMITTED",
  ARCHIVED: "ARCHIVED",
} as const;

export const CASE_TYPES = {
  AR: "AR",
  FS: "FS",
  INCORPORATION: "INCORPORATION",
  TAX_FILING: "TAX_FILING",
  AUDIT: "AUDIT",
  DEBT_RECOVERY: "DEBT_RECOVERY",
  AD_HOC: "AD_HOC",
} as const;

export const PRIORITY = {
  LOW: "LOW",
  NORMAL: "NORMAL",
  HIGH: "HIGH",
  URGENT: "URGENT",
} as const;

export const PAYMENT_STATUS = {
  NOT_APPLICABLE: "NOT_APPLICABLE",
  PENDING: "PENDING",
  PARTIAL: "PARTIAL",
  PAID: "PAID",
  OVERDUE: "OVERDUE",
} as const;

export const TASK_STATUS = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const;

export const DOCUMENT_CATEGORY = {
  INVOICE: "INVOICE",
  PAYMENT_VOUCHER: "PAYMENT_VOUCHER",
  OFFICIAL_RECEIPT: "OFFICIAL_RECEIPT",
  SUPPLIER_INVOICE: "SUPPLIER_INVOICE",
  BANK_STATEMENT: "BANK_STATEMENT",
  IC_CARD: "IC_CARD",
  PASSPORT: "PASSPORT",
  TAX_FORM: "TAX_FORM",
  RESOLUTION: "RESOLUTION",
  ENGAGEMENT_LETTER: "ENGAGEMENT_LETTER",
  AUDITED_REPORT: "AUDITED_REPORT",
  EA_FORM: "EA_FORM",
  FORM_E: "FORM_E",
  OTHER: "OTHER",
} as const;

export const DOCUMENT_STATUS = {
  REQUESTED: "REQUESTED",
  RECEIVED: "RECEIVED",
  CLASSIFIED: "CLASSIFIED",
  OCR_PROCESSED: "OCR_PROCESSED",
  REVIEWED: "REVIEWED",
  SIGNED_RECEIVED: "SIGNED_RECEIVED",
  ORIGINAL_RECEIVED: "ORIGINAL_RECEIVED",
  ARCHIVED: "ARCHIVED",
  DELETED: "DELETED",
} as const;

export const REMINDER_CHANNEL = {
  EMAIL: "EMAIL",
  WHATSAPP: "WHATSAPP",
} as const;

export const REMINDER_STATUS = {
  SCHEDULED: "SCHEDULED",
  DRAFTED: "DRAFTED",
  APPROVED: "APPROVED",
  SENT: "SENT",
  DELIVERED: "DELIVERED",
  FAILED: "FAILED",
  STOPPED: "STOPPED",
} as const;

export const REMINDER_TYPES = {
  AR_1ST: "AR_1ST",
  AR_2ND: "AR_2ND",
  AR_3RD: "AR_3RD",
  FS_1ST: "FS_1ST",
  FS_2ND: "FS_2ND",
  FS_3RD: "FS_3RD",
  PAYMENT: "PAYMENT",
  DEBT_CURRENT: "DEBT_CURRENT",
  DEBT_PRIOR: "DEBT_PRIOR",
  DOCUMENT_REQUEST: "DOCUMENT_REQUEST",
  GENERAL: "GENERAL",
} as const;

export const REVIEW_ITEM_TYPE = {
  REMINDER_DRAFT: "REMINDER_DRAFT",
  OCR_LOW_CONFIDENCE: "OCR_LOW_CONFIDENCE",
  INCORPORATION_DRAFT: "INCORPORATION_DRAFT",
  DISCREPANCY_FINDING: "DISCREPANCY_FINDING",
  REGULATORY_DIGEST: "REGULATORY_DIGEST",
  MBRS_MISMATCH: "MBRS_MISMATCH",
} as const;

export const REVIEW_ITEM_STATUS = {
  NEW: "NEW",
  IN_REVIEW: "IN_REVIEW",
  APPROVED: "APPROVED",
  EDITED_AND_APPROVED: "EDITED_AND_APPROVED",
  REJECTED: "REJECTED",
  NEEDS_MORE_INFO: "NEEDS_MORE_INFO",
} as const;

export const APPROVAL_ACTION = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  EDITED: "EDITED",
  REQUESTED_MORE_INFO: "REQUESTED_MORE_INFO",
} as const;

export const SUBMISSION_STATUS = {
  NOT_READY: "NOT_READY",
  COLLECTING_DOCUMENTS: "COLLECTING_DOCUMENTS",
  READY_FOR_INTERNAL_CHECK: "READY_FOR_INTERNAL_CHECK",
  READY_FOR_SUBMISSION: "READY_FOR_SUBMISSION",
  SUBMITTED: "SUBMITTED",
  SUBMISSION_FAILED: "SUBMISSION_FAILED",
  ARCHIVED: "ARCHIVED",
} as const;

export const ENGAGEMENT_TYPE = {
  SECRETARIAL: "SECRETARIAL",
  ACCOUNTING: "ACCOUNTING",
  TAX: "TAX",
  AUDIT: "AUDIT",
} as const;

// Status label maps for UI display
export const CASE_STATUS_LABELS: Record<string, string> = {
  DRAFT: "Draft",
  ACTIVE: "Active",
  AWAITING_CLIENT: "Awaiting Client",
  AWAITING_INTERNAL_REVIEW: "Awaiting Review",
  BLOCKED: "Blocked",
  READY_FOR_SUBMISSION: "Ready for Submission",
  SUBMITTED: "Submitted",
  ARCHIVED: "Archived",
};

export const DEPARTMENT_LABELS: Record<string, string> = {
  SECRETARIAL: "Secretarial",
  ACCOUNTING: "Accounting",
  TAX: "Tax",
  AUDIT: "Audit",
  MANAGEMENT: "Management",
};
